apiVersion: apps/v1
kind: Deployment
metadata:
  name: cpu-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cpu-app
  template:
    metadata:
      labels:
        app: cpu-app
    spec:
      containers:
      - name: cpu-app
        image: 100xdevs/week-28:latest
        ports:
        - containerPort: 3000
        resources:      # adding resource to bypass the not found utilisation % of machine error / cloud provider specific
          requests:
            cpu: "100m"
          limits:
            cpu: "1000m"

# Check the CPU usage
# kubectl top pods   

# See the hpa average usage
# kubectl get hpa

# Check the number of pods, see as they scale up
# kubectl get pods

# scaling formula
# new desired capacity = (total cpu utilisation / target cpu)